"""create tables

Revision ID: 7a39b45bc7bd
Revises: 
Create Date: 2025-12-08 00:44:23.348916

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7a39b45bc7bd'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('platforms',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('keywords', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_platforms_name'), 'platforms', ['name'], unique=True)
    op.create_table('settings',
    sa.Column('markup_rate', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('ton_rate', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('lang', sa.Enum('ru', 'en', name='lang_enum'), nullable=True),
    sa.Column('balance', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('ref_id', sa.BigInteger(), nullable=True),
    sa.Column('ref_code', sa.String(), nullable=False),
    sa.Column('ref_income', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('favorite_services', postgresql.ARRAY(sa.BigInteger()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['ref_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_users_ref_code'), 'users', ['ref_code'], unique=True)
    op.create_index(op.f('ix_users_user_id'), 'users', ['user_id'], unique=False)
    op.create_table('categories',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('platform_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['platform_id'], ['platforms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transactions',
    sa.Column('transaction_hash', sa.String(length=100), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('rub_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('service', sa.String(length=100), nullable=False),
    sa.Column('payment_link', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('pending', 'success', 'failed', name='status_enum'), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('services',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('api_service_id', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('original_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('language', sa.Enum('ru', 'en', name='lang_enum'), nullable=False),
    sa.Column('time', sa.String(length=100), nullable=True),
    sa.Column('refill', sa.Boolean(), nullable=False),
    sa.Column('cancel', sa.Boolean(), nullable=False),
    sa.Column('min_amount', sa.Integer(), nullable=False),
    sa.Column('max_amount', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_services_api_service_id'), 'services', ['api_service_id'], unique=False)
    op.create_table('orders',
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('link', sa.String(length=500), nullable=False),
    sa.Column('is_done', sa.Boolean(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('orders')
    op.drop_index(op.f('ix_services_api_service_id'), table_name='services')
    op.drop_table('services')
    op.drop_table('transactions')
    op.drop_table('categories')
    op.drop_index(op.f('ix_users_user_id'), table_name='users')
    op.drop_index(op.f('ix_users_ref_code'), table_name='users')
    op.drop_table('users')
    op.drop_table('settings')
    op.drop_index(op.f('ix_platforms_name'), table_name='platforms')
    op.drop_table('platforms')
    # ### end Alembic commands ###
