"""add_min_deposit_rate_to_settings

Revision ID: 8b9eb90782ed
Revises: ef5f9df4e9ff
Create Date: 2026-01-30 20:35:59.708639

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b9eb90782ed'
down_revision: Union[str, Sequence[str], None] = 'ef5f9df4e9ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('settings', sa.Column('min_deposit_rate', sa.Numeric(precision=10, scale=2), nullable=False, server_default='0.00'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('settings', 'min_deposit_rate')
    # ### end Alembic commands ###
