"""change parent_order_id

Revision ID: edba4c8b23a7
Revises: 7a39b45bc7bd
Create Date: 2025-12-10 04:32:12.199457

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'edba4c8b23a7'
down_revision: Union[str, Sequence[str], None] = '7a39b45bc7bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('parent_order_id', sa.BigInteger(), nullable=True))
    op.drop_column('orders', 'order_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('order_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('orders', 'parent_order_id')
    # ### end Alembic commands ###
